name: BMIDE Package Deploy

on: [push]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-files
          path: /files  # Specify the path to the files you want to copy

  use-copied-files:
    runs-on: ubuntu-latest
    needs: copy-files
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-files

      - name: List copied files
        run: |
          ls test-Project/my-files  

      # You can perform other actions like xcopy here if needed
      - name: Example Xcopy command (if applicable)
        run: |
          Xcopy "addition.py" \Copy /E/H/C/I
